---
apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
---
# --- STORAGE (PVC) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-1
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi # Ridotto per minikube, puoi aumentarlo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-2
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
# --- VICTORIA METRICS NODE 1 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-1
  namespace: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
      instance: node-1
  template:
    metadata:
      labels:
        app: victoriametrics
        instance: node-1
    spec:
      containers:
      - name: vm
        image: victoriametrics/victoria-metrics:v1.135.0
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
          - "-httpListenAddr=0.0.0.0:8429"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: data
            mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vm-data-1
---
apiVersion: v1
kind: Service
metadata:
  name: vm-svc-1
  namespace: victoria-metrics
spec:
  ports:
    - port: 8429
      targetPort: 8429
  selector:
    app: victoriametrics
    instance: node-1
---
# --- VICTORIA METRICS NODE 2 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-2
  namespace: victoria-metrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: victoriametrics
      instance: node-2
  template:
    metadata:
      labels:
        app: victoriametrics
        instance: node-2
    spec:
      containers:
        image: victoriametrics/victoria-metrics:v1.135.0
      - name: vm
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
          - "-httpListenAddr=:8429"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: data
            mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vm-data-2
---
apiVersion: v1
kind: Service
metadata:
  name: vm-svc-2
  namespace: victoria-metrics
spec:
  ports:
    - port: 8429
      targetPort: 8429
  selector:
    app: victoriametrics
    instance: node-2
---
# --- SERVICE DI LETTURA (Load Balancer interno) ---
apiVersion: v1
kind: Service
metadata:
  name: vm-read-lb
  namespace: victoria-metrics
spec:
  type: NodePort # Utile per accedere da Minikube
  ports:
    - port: 8429
      targetPort: 8429
      nodePort: 30429
  selector:
    app: victoriametrics
---
# --- CONFIGURAZIONE VMAGENT ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: victoria-metrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'vmagent'
        static_configs:
          - targets: ['localhost:8429']
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
---
# --- RBAC PER VMAGENT ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmagent-sa
  namespace: victoria-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-cr
rules:
  # Blocco 1: Risorse standard del cluster
  - apiGroups: [""]
    resources: 
      - nodes
      - nodes/proxy
      - nodes/metrics
      - nodes/spec
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  # Blocco 2: URL non-risorsa (per le metriche globali)
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-cr
subjects:
  - kind: ServiceAccount
    name: vmagent-sa
    namespace: victoria-metrics
---
# --- DEPLOYMENT VMAGENT (Mirroring Mode) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      serviceAccountName: vmagent-sa
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:v1.101.0
        args:
          - "-promscrape.config=/etc/prometheus/prometheus.yml"
          # Scrive contemporaneamente su entrambi i nodi
          - "-remoteWrite.url=http://vm-svc-1:8429/api/v1/write"
          - "-remoteWrite.url=http://vm-svc-2:8429/api/v1/write"
          - "-remoteWrite.tmpDataPath=/tmp/vmagent-buffer"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: config
            mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: vmagent-config
