apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
---
# --- STORAGE (PVC) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-1
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-2
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
# --- VICTORIA METRICS NODE 1 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-1
  namespace: victoria-metrics
spec:
  replicas: 1
  minReadySeconds: 60 # Aspetta che il nodo sia stabile prima di proseguire
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: victoriametrics
      instance: node-1
  template:
    metadata:
      labels:
        app: victoriametrics
        instance: node-1
    spec:
      terminationGracePeriodSeconds: 60
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: vm
        image: victoriametrics/victoria-metrics:v1.110.0
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
          - "-httpListenAddr=0.0.0.0:8429"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: data
            mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vm-data-1
---
# --- VICTORIA METRICS NODE 2 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-2
  namespace: victoria-metrics
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: victoriametrics
      instance: node-2
  template:
    metadata:
      labels:
        app: victoriametrics
        instance: node-2
    spec:
      terminationGracePeriodSeconds: 60
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: vm
        image: victoriametrics/victoria-metrics:v1.110.0
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
          - "-httpListenAddr=:8429"
        ports:
          - containerPort: 8429
        volumeMounts:
          - name: data
            mountPath: /storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vm-data-2
---
# SERVIZI E CONFIGMAP (Invariati ma aggiornati nel namespace)
apiVersion: v1
kind: Service
metadata:
  name: vm-svc-1
  namespace: victoria-metrics
spec:
  ports:
    - port: 8429
      targetPort: 8429
  selector:
    app: victoriametrics
    instance: node-1
---
apiVersion: v1
kind: Service
metadata:
  name: vm-svc-2
  namespace: victoria-metrics
spec:
  ports:
    - port: 8429
      targetPort: 8429
  selector:
    app: victoriametrics
    instance: node-2
---
apiVersion: v1
kind: Service
metadata:
  name: vm-read-lb
  namespace: victoria-metrics
spec:
  type: NodePort
  ports:
    - port: 8429
      targetPort: 8429
      nodePort: 30429
  selector:
    app: victoriametrics
---
# --- VMAGENT CONFIG & DEPLOY ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: victoria-metrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'vmagent'
        static_configs:
          - targets: ['localhost:8429']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:v1.110.0
        args:
          - "-promscrape.config=/etc/prometheus/prometheus.yml"
          - "-remoteWrite.url=http://vm-svc-1:8429/api/v1/write"
          - "-remoteWrite.url=http://vm-svc-2:8429/api/v1/write"
          - "-remoteWrite.tmpDataPath=/tmp/vmagent-buffer"
        volumeMounts:
          - name: config
            mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: vmagent-config
