apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-1
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-data-2
  namespace: victoria-metrics
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
# --- STORAGE NODE 1 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-1
  namespace: victoria-metrics
spec:
  replicas: 1
  strategy:
    type: Recreate # Forza lo spegnimento prima del riavvio per liberare il volume
  selector:
    matchLabels:
      app: vm-node-1
  template:
    metadata:
      labels:
        app: vm-node-1
    spec:
      terminationGracePeriodSeconds: 60 # Tempo per il flush dei dati e rimozione lock
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: victoria-metrics
        image: victoriametrics/vmstorage:v1.123.0
        ports:
        - containerPort: 8482
        - containerPort: 8400
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: vm-data-1
---
# --- STORAGE NODE 2 ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-node-2
  namespace: victoria-metrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vm-node-2
  template:
    metadata:
      labels:
        app: vm-node-2
    spec:
      terminationGracePeriodSeconds: 60
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: victoria-metrics
        image: victoriametrics/vmstorage:v1.123.0
        ports:
        - containerPort: 8482
        - containerPort: 8400
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: vm-data-2
---
# --- VMAGENT (Collector) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      hostAliases:
      - ip: "140.82.121.4"
        hostnames:
        - "github.com"
      containers:
      - name: vmagent
        image: victoriametrics/vmagent:v1.110.0
        args:
          - "-remoteWrite.url=http://victoria-metrics-service:8480/insert/0/prometheus"
        ports:
        - containerPort: 8429
---
# --- SERVICE PER ACCESSO UI E INSERIMENTO ---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-service
  namespace: victoria-metrics
spec:
  type: NodePort
  ports:
  - name: http-select
    port: 8481
    targetPort: 8481
    nodePort: 30428 # Porta per la tua UI
  - name: http-insert
    port: 8480
    targetPort: 8480
  selector:
    # Nota: questo service dovrebbe puntare a un vmselect in un cluster vero, 
    # qui lo configuriamo per bilanciare sui nodi o verso il componente di query
    app: vm-node-1
